version: '3.3'

services:
  db:
    image: postgres:12.0-alpine
    ports: 
     - "5432:5432"
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
#    command: bash -c "createdb --username=root testdb"

  web:
    build: .
    restart: always
    ports:
     - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env 

volumes:
  db_value:
