"""subscribes

Revision ID: 027238d703bf
Revises: db31653e4bcd
Create Date: 2023-03-21 09:55:37.338296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '027238d703bf'
down_revision = 'db31653e4bcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribes',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('instrument', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['instrument'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('instrument', 'address', name='instrument_address_constraint')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribes')
    # ### end Alembic commands ###
