"""instrument

Revision ID: 39fdd8c9d5b6
Revises: 
Create Date: 2023-03-17 21:36:07.192048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39fdd8c9d5b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument')
    )
    op.create_index(op.f('ix_instruments_id'), 'instruments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instruments_id'), table_name='instruments')
    op.drop_table('instruments')
    # ### end Alembic commands ###
