"""index

Revision ID: 80d7c818c8d4
Revises: bdc44dca98bd
Create Date: 2023-03-22 19:08:23.480437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d7c818c8d4'
down_revision = 'bdc44dca98bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_subscribes_instrument'), 'subscribes', ['instrument'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribes_instrument'), table_name='subscribes')
    # ### end Alembic commands ###
