"""orders

Revision ID: cb24abc10f2d
Revises: 
Create Date: 2023-03-26 19:14:49.726776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb24abc10f2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('instrument', postgresql.ENUM('eur_usd', 'eur_rub', 'usd_rub', name='instrument'), nullable=False),
    sa.Column('side', postgresql.ENUM('buy', 'sell', name='orderside'), nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'filled', 'rejected', 'cancelled', name='orderstatus'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('change_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
