"""models

Revision ID: d301637bb6b1
Revises: 
Create Date: 2023-03-25 18:32:48.401284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd301637bb6b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('orders',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('instrument', sa.Integer(), nullable=False),
    sa.Column('side', postgresql.ENUM('buy', 'sell', name='orderside'), nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'filled', 'rejected', 'cancelled', name='orderstatus'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('change_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument'], ['instruments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('quotes',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('instrument', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('bid', sa.DECIMAL(), nullable=False),
    sa.Column('offer', sa.DECIMAL(), nullable=False),
    sa.Column('min_amount', sa.DECIMAL(), nullable=False),
    sa.Column('max_amount', sa.DECIMAL(), nullable=False),
    sa.ForeignKeyConstraint(['instrument'], ['instruments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('subscribes',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('instrument', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['instrument'], ['instruments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('instrument', 'address', name='instrument_address_constraint')
    )
    op.create_index(op.f('ix_subscribes_instrument'), 'subscribes', ['instrument'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribes_instrument'), table_name='subscribes')
    op.drop_table('subscribes')
    op.drop_table('quotes')
    op.drop_table('orders')
    op.drop_table('instruments')
    # ### end Alembic commands ###
